// GENERATED by yaksaro-hq — DO NOT EDIT.
// 이 파일을 직접 고치면 다음 동기화 때 덮어써진다.
// 값을 바꾸려면: yaksaro-hq/brand/DECISIONS.md 에 근거를 남기고 tokens.json 을 고칠 것.
// 재생성: node scripts/sync-brand.mjs --write --only care


export const BRAND_COLORS = {
  green600: '#0E6E54',
  green700: '#084B3A',
  green300: '#89CCB3',
  green100: '#C8E6D5',
  green50: '#E3F2EB',
  lime300: '#D9F25C',
  blue500: '#4A8FCC',
  blue700: '#2E6CA6',
  warning: '#E8A817',
  error: '#C9423F',
  neutral900: '#13261F',
  neutral800: '#1E3A2F',
  neutral700: '#2D4A3E',
  neutral600: '#3D4A44',
  neutral500: '#5A6B62',
  neutral400: '#8A9890',
  neutral300: '#C8CBC3',
  neutral200: '#E2E4DE',
  neutral100: '#F0F1EC',
  neutral50: '#FAFAF5',
  pageBg: '#EFEBE2',
  warningBg: '#FEF9E7',
  errorBg: '#FEF2F2',
  infoBg: '#EFF6FF',
  successBg: '#E3F2EB',
  warningText: '#92600A',
  warningTextSoft: '#7A5A00',
  infoText: '#1E5BA8',
  saturday: '#2E6CA6',
} as const;

/** 지그재그 'ㄹ' 심볼. 세 저장소에 복붙돼 있던 것을 여기로 모았다. */
export const LOGO_VIEWBOX = '0 0 100 100';
export const LOGO_MARK_PATH = 'M 22 22 L 78 22 L 78 50 L 22 50 L 22 78 L 78 78';
export const LOGO_STROKE_WIDTH = 18;

export const LOGO_BADGE = {
  rect: { x: 2, y: 2, width: 96, height: 96, rx: 22 },
  fill: BRAND_COLORS.green600,
  stroke: BRAND_COLORS.neutral50,
  dash: { stroke: BRAND_COLORS.lime300, strokeWidth: 3.5, strokeDasharray: '6 4' },
} as const;

export const LOGO_PLAIN_STROKE = BRAND_COLORS.neutral900;
